### ISSUE TITLE
add dotenv to examples

### ISSUE THREAD

**Issue by philtsip** [daily-co/dailyai#76]
Most of the examples, for instance 06a-image-sync.py, need dotenv imported to grab the variables from the .env file

from dotenv import load_dotenv
load_dotenv()

without it, you get the following non-str key serialization error:

foundational$ python 06a-image-sync.py -u "[MY ROOM URL]" -k "[MY KEY]"
Using cache found in /Users/ddd/.cache/torch/hub/snakers4_silero-vad_master

20 2024-03-19 00:37:03,467 🎬 Starting frame consumer thread
--- Logging error ---
Traceback (most recent call last):
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/site-packages/dailyai/services/ai_services.py", line 54, in run
    async for output_frame in self.process_frame(frame):
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/site-packages/dailyai/services/ai_services.py", line 115, in process_frame
    async for audio_chunk in self.run_tts(text):
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/site-packages/dailyai/services/elevenlabs_ai_service.py", line 34, in run_tts
    async with self._aiohttp_session.post(
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/site-packages/aiohttp/client.py", line 599, in _request
    resp = await req.send(conn)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 712, in send
    await writer.write_headers(status_line, self.headers)
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/site-packages/aiohttp/http_writer.py", line 129, in write_headers
    buf = _serialize_headers(status_line, headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/ddd/opt/anaconda3/envs/py311/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting

**Comment by aconchillo** [comment]
Hi @philtsip . `dotenv` was added in this commit https://github.com/daily-co/daily-ai-sdk/commit/a573277a106a7a3050a693daed7bc02316afbf24 a few days ago. Can you pull the latest changes and see if this has fixed it for you? Thanks!

**Comment by aconchillo** [comment]
I believe this is all fixed now. Thank you @philtsip !
